---
title: "cooccurrence_ordination"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warning = -1)
setwd("/Volumes/Backup_1/Marie/Thesis/Rwanda/Lab work/03_NiCE_Chip/final_data")
library(tidyverse)
library(vegan)
source("cooccurrence_permanova.R")
```


```{r}
#generate dissimilarity matrix to test for differences in community composition


nice_1_dist <- as.matrix(spearman.dist(nice_1_cor_mat))
nice_2_dist <- as.matrix(spearman.dist(nice_2_cor_mat))
nice_3_dist <- as.matrix(spearman.dist(nice_3_cor_mat))
nice_4_dist <- as.matrix(spearman.dist(nice_4_cor_mat))
nice_5_dist <- as.matrix(spearman.dist(nice_5_cor_mat))
nice_6_dist <- as.matrix(spearman.dist(nice_6_cor_mat))
nice_all_dist <- as.matrix(spearman.dist(nice_all_cor_mat))

```

```{r}
#visualize dissimilarity matrix as NMDS in vegan package

nice_1_NMDS <- metaMDS(nice_1_dist)
stressplot(nice_1_NMDS)
nice_1_scores <- as.data.frame(scores(nice_1_NMDS))
plot(nice_1_NMDS)

nice_2_NMDS <- metaMDS(nice_2_dist)
stressplot(nice_2_NMDS)
nice_2_scores <- as.data.frame(scores(nice_2_NMDS))

nice_3_NMDS <- metaMDS(nice_3_dist)
stressplot(nice_3_NMDS)
nice_3_scores <- as.data.frame(scores(nice_3_NMDS))

nice_4_NMDS <- metaMDS(nice_4_dist)
stressplot(nice_4_NMDS)
nice_4_scores <- as.data.frame(scores(nice_4_NMDS))

nice_5_NMDS <- metaMDS(nice_5_dist)
stressplot(nice_5_NMDS)
nice_5_scores <- as.data.frame(scores(nice_5_NMDS))

nice_6_NMDS <- metaMDS(nice_6_dist)
stressplot(nice_6_NMDS)
nice_6_scores <- as.data.frame(scores(nice_6_NMDS))
plot(nice_6_NMDS)

set.seed(123)
nice_all_NMDS <- metaMDS(dist=nice_all_dist) #does not converge
#nice_all_pca <- rda(nice_all_cor_mat)
stressplot(nice_all_NMDS)
nice_all_scores <- as.data.frame(scores(nice_all_NMDS)) 
nice_all_scores$timepoint <- nice$timepoint

plot(nice_all_NMDS)
head(nice_all_scores)

f <- as.matrix(nice_all_NMDS$diss)

nice_mat_all <- as.matrix(nice_all_dist)



```

```{r}
#visualize NMDS with all timepoints to test for differences
#use phyloseq package for ease
setwd("/Volumes/Backup_1/Marie/Thesis/Rwanda/Lab work/03_NiCE_Chip/metadata")
library(phyloseq)
library(SNCAnalysis)


#phyloseq tax_table() object = matrix of taxonomy/grouping info for each set of primers 

nice_tax <- readr::read_csv("nice_tax_data.csv")
head(nice_tax)

nice_tax <- nice_tax %>%
   mutate(primer_pair = paste(primer_F, primer_R, sep= " / "))

#coerce into a matrix 
test_tax <- tax_table(nice_tax)
taxa_names(test_tax) <- nice_tax$probe

nice_samples <- SNCAnalysis::full_dat 

rownames(nice_samples) <- nice_samples$sample
nice_samples <- nice_samples[,-1]

#convert to physeq
# sample_table <- sample_data(nice_samples)
# head(sample_table)
# 
# 
# #otu table
# abund_mat <- otu_table(abund_df, taxa_are_rows=TRUE)
# 
# #create phyloseq object
# sample_names(abund_mat)
# sample_names(sample_table)
# sample_names(test_tax)
# 
# nice_physeq <- phyloseq(abund_mat, test_tax, sample_table)
# 
# 
# #nice_physeq_NMDS <- ordinate(nice_physeq, method="NMDS", distance=nice_all_dist)
# 
# nice_physeq_NMDS <- ordinate(nice_physeq, method = "NMDS")
# 
# 
# p1 <- plot_ordination(nice_physeq, nice_physeq_NMDS, type="taxa", color="ta3") +
#   theme_bw()
# 
# g <- scales::brewer_pal(type="seq", palette="RdBu")
# brewed <- g(10)
# 
# p2 <- plot_ordination(nice_physeq, nice_physeq_NMDS, type="samples", color="timepoint", shape="location")+
#   theme_bw() +
#   ggtitle("Sample plot: timepoint") +
#   scale_color_stepsn(colors=brewed) 
# 
# p2 + stat_ellipse(mapping=aes(data=centroids))
#   
# #ordiellipse(nice_physeq_NMDS, groups=as.factor(nice_samples$timepoint), label=TRUE)
# 
# centroids <- as.data.frame(ord.cent$factors$centroids) 
# rownames(centroids) <- 1:6
# centroids$timepoint <- rownames(centroids)
# 
# 
# ord.cent <- envfit(nice_physeq_NMDS~as.factor(timepoint), data=nice_samples) #p=0.001
# envfit(nice_physeq_NMDS~location, data=nice_samples) #p=0.07
# 
# ?stat_ellipse
# 
# sample_table$
#   
#   #scale_color_brewer(type="seq", palette="Dark2")
# 
# 
# p3 <- plot_ordination(nice_physeq, nice_physeq_NMDS, type="samples", color="location")+
#   theme_bw()+
#   ggtitle("Sample plot: location")
# p3

```

